### PR TITLE
React dialog

### PR DESCRIPTION
**Pull request by pelikhan**
+ full rebuild of shims
+ removed serial
+ add qrCode/debugger as experiemnts
Fix for https://github.com/Microsoft/pxt-adafruit/issues/987

### CODE REVIEW

**Comment by abchatra** [comment]
Thanks

**Comment by pelikhan** [comment]
Notice about Mac Bootloader update still needed though.

**Comment by abchatra** [comment]
image

**Comment by abchatra** [comment]
There is an extra $

**Comment by riknoll** [comment]
https://github.com/Microsoft/pxt-adafruit/pull/996

**Pull request merged**
