### PR TITLE
cloud project

### PR DESCRIPTION
**Pull request by anahitagharai**
This is the cloud project's documentation! @ganicke @riknoll

### CODE REVIEW

**Comment by ganicke** [comment]
Moving this to #806 for review/editing. We'll close this one after #806 is in.

**Comment by anahitagharai** [comment]
yeah i got it from google images, is that ok? @ganicke

**Comment by riknoll** [comment]
@anahitagharai nope. We can't check in someone else's image

**Comment by ganicke** [comment]
I gotta fix going for the song image, standby...

**Comment by ganicke** [comment]
Merged #806, closing this one.

**Pull request closed without merging**
