### PR TITLE
power glove -> energy glove

### PR DESCRIPTION
**Pull request by pelikhan**
Power Glove is an existing product.

### CODE REVIEW

**Comment by riknoll** [comment]
@ganicke https://en.wikipedia.org/wiki/Power_Glove

**Comment by ganicke** [comment]
K, I know. Hmm, "Power Grab", "Power FIst", "Zap and Slap". Coming up short here...

**Comment by riknoll** [comment]
Power Gauntlet?

**Comment by ganicke** [comment]
Mega Mitten, Wonder Glove

**Comment by pelikhan** [comment]
So much choice. U pick!

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by ganicke** [comment]
Argh! Wonder/Mega Glove is taken! Power Gauntlet is from Green Lantern. Is that a TM?

Oh, let's stick with Energy Glove.

**Pull request merged**
