### PR TITLE
Edits for 'Coffee Cup Lamp' project

### PR DESCRIPTION
**Pull request by ganicke**
I decided to just copy and make a branch here. If this is good to go, then close #794 and delete the branch from the fork. Check to make sure I didn't wreck anything :grinning:

Should add to the gallery somewhere. Don't have a category for it yet.

- [x] Resize images
- [x] Put **setBrightness** into **onStart** in _code.md_
- [x] A few text edits here and there.

RE: #794

### CODE REVIEW

**Comment by riknoll** [comment]
Thanks @ganicke ! Do you have any tips on how you bulk-resize the images for these lessons?

**Comment by ganicke** [comment]
Resizing images: ImageMagik? 

``magick '*.jpg' -resize 800x600``

Also, resizing we could add some tooling and use imageMagik APIs maybe. Should have a ``pxt checkdocs`` option to scan for "valid" image sizes.

**Comment by riknoll** [comment]
That's a good idea, maybe we should add a PXT command that does the resizing too.

**Comment by riknoll** [comment]
Ugh, they have a custom license. Guess I'll find some other library

**Comment by ganicke** [comment]
Well, that's a drag.

**Pull request merged**
