### PR TITLE
smaller hero page

### PR DESCRIPTION
**Pull request by pelikhan**
850k -> 100k.

### CODE REVIEW

**Comment by microsoftsam** [comment]
Nice. What did you do, because I'm going to have to update that.

**Comment by microsoftsam** [comment]
Is it just exported to JPEG?

**Comment by pelikhan** [comment]
Using .jpg instead of .png compresses better for photo-like images. Old images left unchanged.

**Comment by microsoftsam** [comment]
Cool. Will do so in the future. Thanks!

**Comment by pelikhan** [comment]
Yes.

**Pull request merged**
