### PR TITLE
Some word changes to reduce policheck hits

### PR DESCRIPTION
**Pull request by ganicke**
Make a few easy word changes to help reduce Policheck false positives.

### CODE REVIEW

**Review by abchatra — APPROVED** [review]
I though orient was a proper verb. What is wrong with it? Looks good overall

**Comment by ganicke** [comment]
The word "orient" is fine when used to describe positioning. I'm just replacing it with a synonym to avoid the false positive.

**Comment by abchatra** [comment]
You can just ignore the false positive too. Don't have to fix all the false positives. Only if it is true positive we have to fix it. Otherwise it is optional.

**Comment by ganicke** [comment]
Right, but those were easy so I thought why not. They won't show on the list next time.

**Pull request merged**
