### PR TITLE
CN projects image exchange

### PR DESCRIPTION
**Pull request by ganicke**
- [x] Switch thumbs for cards with project pics
- [x] Use better pics for page banners
- [x] Insert "Prepare" section to contain level, duration, and materials list

RE: #925

### CODE REVIEW

**Comment by ganicke** [comment]
Do we want to switch out the completed project gifs with embed YouTube links?

**Comment by Jaqster** [comment]
Yeah, the gifs are pretty bad resolution - good idea to switch out with an embedded video

**Comment by pelikhan** [comment]
YouTube gets blocked in schools. What is the fallback?

Get Outlook for iOS<https://aka.ms/o0ukef>

________________________________

**Comment by ganicke** [comment]
It looks like all of the project drops have the original mp4 videos. I could try encoding new GIFs. Maybe I can get better results than those that were handed off. I will have to slim the frame count to keep the download size down though.

**Pull request merged**
