### PR TITLE
Release 3.8 again 

### PR DESCRIPTION
**Pull request by samelhusseini**
With https://github.com/Microsoft/pxt/pull/4145

Ready for release.

### CODE REVIEW

**Comment by abchatra** [comment]
Can I sanity test /beta before releasing it?

**Comment by abchatra** [comment]
This change includes change for both bump as well as release.

**Comment by samelhusseini** [comment]
Yes. By design. Because master is ahead. Don't mind that.

**Comment by abchatra** [comment]
Oh ok makes sense.

**Pull request merged**
