### PR TITLE
New ts changes

### PR DESCRIPTION
**Pull request by riknoll**
For https://github.com/Microsoft/pxt/pull/3559

### CODE REVIEW

**Comment by riknoll** [comment]
Ignore the build

**Comment by riknoll** [comment]
Build should be fixed by https://github.com/Microsoft/pxt/pull/3637

**Comment by mmoskal** [comment]
Is this going in anytime soon?

**Comment by pelikhan** [comment]
Push it in. The new version looks stable.

________________________________

**Pull request merged**
