### PR TITLE
Integrate download instructions provided by Adafruit

### PR DESCRIPTION
**Pull request by microsoftsam**
screen shot 2017-11-14 at 1 43 16 pm

Let the feedback start rolling in!

Requires: https://github.com/Microsoft/pxt/pull/3477

### CODE REVIEW

**Comment by Jaqster** [comment]
Step 1 - "Plug the USB cable from your computer to the Circuit Playground Express"
Step 2 - "Press and release the Reset button in the middle of the Circuit Playground Express. You may need to do this a couple times until all the lights turn green."
Step 3 - "Click the Pink Download button to download your program file from the browser"
Step 4 - "Save, or drag and drop your program file to the CPLAYBOOT drive on your computer"

**Comment by Jaqster** [comment]
I don't like the last picture - can we replace with a more simplified graphic?

**Comment by microsoftsam** [comment]
@Jaqster for step 3. It's already done at that point. ie: They have clicked on the download button and it's been downloaded on their computer. The steps at that point are to get the board in programming mode, and then drag the file that's been downloaded.

**Comment by microsoftsam** [comment]
I agree, the last picture could be simplified. The other issue with the last picture is that it's platform specific. 
We are able to determine what platform we're on and provide a different picture for each. If Adafruit can supply a Mac and Chrome book one.

**Pull request merged**
