### PR TITLE
Add animation images

### PR DESCRIPTION
**Pull request by microsoftsam**
screen shot 2017-10-15 at 12 32 03 pm

Relies on https://github.com/Microsoft/pxt-common-packages/pull/124 to surface field editor.

Relies on these two as well: 
https://github.com/Microsoft/pxt-adafruit/pull/363
https://github.com/Microsoft/pxt/pull/3240

### CODE REVIEW

**Comment by microsoftsam** [comment]
Svgs aren't user facing, don't want to optimize so we don't lose any details in the SVG making.

**Comment by pelikhan** [comment]
You can use the optimized version in the editor, and keep the full versions somewhere else.

**Comment by pelikhan** [comment]
Oh we use rendered png. Never mind.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by microsoftsam** [comment]
:D

**Comment by Jaqster** [comment]
Love them! :-)

**Pull request merged**
