### PR TITLE
Rename external to neopixel

### PR DESCRIPTION
**Pull request by abchatra**
Renamed

### CODE REVIEW

**Comment by pelikhan** [comment]
I would make it plural. what do the native english people thing? @ganicke

**Comment by abchatra** [comment]
We call "Light" not "Lights". I am for NeoPixel.  @ganicke what do you think?

**Comment by pelikhan** [comment]
It's all singular on learn.adafruit.com. Let's stick with singular.

**Comment by ganicke** [comment]
Cool with it - albeit a late comment. Light docs PRs will need a slight realignment once the all the light changes are in.

**Pull request merged**
