### PR TITLE
Partner updates for 'Legendary Gauntlets'

### LINKED ISSUE #1182: Update Wonder Woman project text
Hi Galen.
I swear, we'll put this project to bed soon!
We got yet another round of feedback from Warner Brothers, and they want us to make some changes.
https://makecode.adafruit.com/projects/wonder-woman-gauntlets 

- [x] Project Title - switch the title of the project from "Wonder Woman Gauntlets" to "Legendary Gauntlets".  Don't worry about updating the Home Page
image

- [x] Update the header from "Wonder Woman Gauntlets" to "Legendary Gauntlets inspired by WONDER WOMAN 1984"
image

- [x] Add text to the bottom of the page "WONDER WOMAN 1984 TM & © DC and WBEI. RATED PG-13"
image

### PR DESCRIPTION
**Pull request by ganicke**
Put in title and copyright updates for "Wonder Woman Gauntlets" (now "Legendary Gauntlets").

BTW, I did add "Legendary" to the Home Screen card. Please review that- https://github.com/microsoft/pxt-adafruit/pull/1183/commits/b18896c0f58b9b8f640183d8bc0e594eb447ced6

Closes #1182

### CODE REVIEW

**Comment by Jaqster** [comment]
Wow that was quick!  Thanks Galen!  
Sorry, I have another update request from them though...   They would like to insert this image on the top of the page somewhere: 
WWmovie

Is that possible?

**Comment by ganicke** [comment]
Sure, but is it big enough? This is thumbnail sized.

**Comment by Jaqster** [comment]
Let me see if I can get a bigger version of this...

**Comment by ganicke** [comment]
No, I think it works ok in the avatar box...

image

**Comment by Jaqster** [comment]
Looks great!  Thank you!

**Pull request merged**
