### PR TITLE
Lightmonster act 

### PR DESCRIPTION
**Pull request by audreyctseng**
Created Make page for Light Monster project in Circuit Playground; finished up youtube links and descriptions for each step in construction.

### CODE REVIEW

**Comment by ganicke** [comment]
Reviewing...

**Comment by riknoll** [comment]
Thanks for taking a look @ganicke !

**Comment by abchatra** [comment]
👍

**Comment by abchatra** [comment]
👏 Can we add this the list of projects which show up in Make?

**Comment by riknoll** [comment]
@audreyctseng can you add an entry to `docs/projects.md` for this project?

**Comment by audreyctseng** [comment]
I think a page was already created--- I saw that Galen had made edits to that intro page too- the only thing I haven’t done is film a video or take a picture of the finished product for the introduction page

**Comment by abchatra** [comment]
Also add entry to docs/summary.md

**Pull request merged**
